OUTPUT_ROOT_DIR: './outputs'

DATA:
  PATH: '../CheXpert-v1.0-small/'
  BATCH_SIZE: 100

SOLVER:
  BASE_LR: 1.0e-4
  NUM_ITERS: 17640
  VAL_INTERVAL: 1
  MIXUP_ALPHA: 0
  WEIGHT_DECAY: 1.0e-4
  SCHEDULER_STEP_SIZE: 5880