OUTPUT_ROOT_DIR: './outputs'

DATA:
  PATH: '../CheXpert-v1.0-small/'
  BATCH_SIZE: 100
  NUM_WORKERS: 0

INPUT:
  IMAGE_CHANNEL: 3

SOLVER:
  BASE_LR: 0.001
  NUM_ITERS: 2000
  VAL_INTERVAL: 1
  MIXUP_ALPHA: 0
  WEIGHT_DECAY: 0
  SCHEDULER_STEP_SIZE: 15